Cargo.toml, src/models.rs, src/models/backend/transactions.rs, src/models/converters/mod.rs, src/models/converters/transactions.rs, src/models/service/mod.rs, src/models/service/transactions.rs, src/services/transactions.rs
- Added transaction backend model loosely based on the swagger
- Added a naïve converter function for the current short implementation of transaction struct
=> Transaction models

Cargo.toml, src/models/backend/transactions.rs, src/models/commons.rs, src/models/converters/transactions.rs, src/services/transactions.rs
Closes #4 
Rough polymorphic deserialisation implemented. Hardcoded values for `tx_type` used, not ideal.
Should test and see what happens when a new value is introduced.
=> Added polymorphic deserialization for transactions

Procfile, RustConfig, src/models/backend/mod.rs, src/models/backend/transactions.rs, src/models/backend/transfers.rs, src/models/commons.rs, src/models/converters/mod.rs, src/models/converters/transactions.rs, src/models/converters/transfers.rs, src/models/service/transactions.rs, src/services/transactions.rs
Changes:
- Heroku deployment
- Made an enum focused (de)serialisation approach
- Added Erc721 type
=> Added transafer DTO

src/models/backend/transfers.rs, src/models/commons.rs, src/models/converters/transactions.rs, src/models/converters/transfers.rs, src/models/service/transactions.rs
- Handled the backend `Transfer` class for generating transactions types.
- Added different types for `TransferInfo` depending on the transfer type.
=> Polymorphic serialisation for Transaction::Transfers

src/main.rs, src/models/backend/transactions.rs, src/models/commons.rs, src/models/converters/transactions.rs, src/models/service/transactions.rs, src/services/transactions.rs, src/utils.rs
There still needs to be a correct fetching of ERC20 and ERC721 token info
=> Multisig TXs mapping paths

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Update issue templates (#19)
- Added bug template
- Added feature template
- It is not possible to add a defaul project
=> Update issue templates (#19)

.env.sample, README.md, Rocket.toml, src/cache.rs, src/main.rs, src/routes/transactions.rs, src/services/transactions.rs
See #17 
- Added redis
- Added caching macro
=> Caching via redis (#17)

src/models/backend/transactions.rs, src/models/converters/transactions.rs, src/models/converters/transfers.rs, src/models/service/transactions.rs, src/services/transactions.rs, src/utils.rs
- Status calculation still missing (depends on #28)
Closes #25 (and maybe #24 too?)
=> Closes #24 and closes #25 - Domain types and Module Transaction mapping into custom

Cargo.toml, src/models/backend/about.rs, src/models/backend/transactions.rs, src/models/backend/transfers.rs, src/models/converters/transactions.rs, src/models/converters/transfers.rs, src/models/service/transactions.rs, src/providers/info.rs, src/routes/transactions.rs, src/services/transactions.rs, src/utils.rs, src/utils/context.rs
Closes #27: Map multisig tx
Closes #26: Map ethereum tx
- Remove ethereum-types, because Address cannot handle checksum properly
- Add host method to context
=> Closes #27 and Closes #26: Map multisig and ethereum tx

.env.sample, src/cache.rs, src/config/mod.rs, src/models/commons.rs, src/models/service/transactions.rs, src/providers/info.rs, src/routes.rs, src/routes/transactions.rs, src/services/transactions.rs, src/utils.rs, src/utils/context.rs
=> Closes #32 query parameter extraction for pagination links

Cargo.toml, src/models/backend/transactions.rs, src/models/backend/transfers.rs, src/models/commons.rs, src/models/converters/transactions.rs, src/models/converters/transactions/details.rs, src/models/converters/transactions/macros.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/summary.rs, src/models/converters/transfers.rs, src/models/service/transactions.rs, src/models/service/transactions/details.rs, src/models/service/transactions/list.rs, src/models/service/transactions/mod.rs, src/models/service/transactions/summary.rs, src/providers/info.rs, src/routes/transactions.rs, src/services/about.rs, src/services/mod.rs, src/services/transactions_details.rs, src/services/transactions_list.rs, src/utils/cors.rs, src/utils/mod.rs
- Closes #39: Add transaction details endpoint
=> Closes #39: Add transaction details endpoint

src/models/converters/transactions/details.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/summary.rs
Closes #46: Check if safe is involved in transfer
=> Closes #46: Check if safe is involved in transfer

src/models/converters/mod.rs, src/models/converters/transactions/details.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/summary.rs, src/models/converters/transfers.rs, src/models/service/transactions/mod.rs, src/services/transactions_details.rs
Closes #48: Add transfer direction
=> Closes #48: Add transfer direction

.env.sample, src/config/mod.rs, src/main.rs, src/models/backend/mod.rs, src/models/backend/webhooks.rs, src/routes/hooks.rs, src/routes/mod.rs, src/services/hooks.rs, src/services/mod.rs
Added endpoint for webhook (#40)
- Added new env variable `WEBHOOK_TOKEN` that is used to verify interactions via the webhook endpoint
=> Added endpoint for webhook (#40)

.env.sample, src/routes/hooks.rs, src/services/hooks.rs, src/utils/cache.rs
Closes #40: Cache invalidation via webhook
=> Closes #40: Cache invalidation via webhook

Cargo.toml, src/models/converters/transactions/macros.rs, src/models/converters/transactions/summary.rs, src/models/converters/transactions/test.rs, src/models/service/transactions/mod.rs, src/services/transactions_details.rs, src/services/transactions_list.rs
Closes #50 
Using `log::debug`
=> Closes #50 Changed println! for debug!

Cargo.toml, src/config/mod.rs, src/models/service/about.rs
Closes #70 
- Pointed to the right env variable
=> Closes #70 Wrong env var name

.travis.yml, README.md
=> Close #21 Travis

.travis.yml, Dockerfile, README.md, scripts/deploy_docker.sh, src/config/mod.rs, src/providers/info.rs, src/routes/about.rs, src/routes/mod.rs, src/routes/transactions.rs
Closes #64: deploy to docker
- Add deployment script
- Trigger deployment script in travis
- Added env variables for docker
- DOCKER_PASSWORD and DOCKER_USERNAME
- DOCKERHUB_ORG and DOCKERHUB_PROJECT (set in .travis.yml)
- Extracted about page logic
=> Closes #64: deploy to docker

src/models/backend/transactions.rs, src/models/commons.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/tests/summary.rs, src/models/converters/transactions/tests/transfer_type_checks.rs, src/models/mod.rs, src/models/tests/commons.rs, src/models/tests/mod.rs, src/utils/mod.rs
Closes #77 
- `Parameter.value` can either be a json string or array: handled both cases
=> Close #77 polymorphic params

.env.sample, Cargo.toml, src/main.rs, src/routes/about.rs, src/routes/mod.rs
- Added `env_logger` for simple logging
- Added about endpoint to query about from backbone service
=> Add simple logger and backbone about endpoint

Cargo.toml
- https://doc.rust-lang.org/cargo/reference/profiles.html#debug
- https://doc.rust-lang.org/cargo/reference/profiles.html#release
=> Enable debug for release build

src/json/commons/data_decoded_add_owner_with_threshold.json, src/json/commons/data_decoded_change_master_copy.json, src/json/commons/data_decoded_change_threshold.json, src/json/commons/data_decoded_disable_module.json, src/json/commons/data_decoded_enable_module.json, src/json/commons/data_decoded_exec_transaction_from_module.json, src/json/commons/data_decoded_remove_owner.json, src/json/commons/data_decoded_set_fallback_handler.json, src/json/commons/data_decoded_swap_owner.json, src/json/mod.rs, src/models/converters/data_decoded.rs, src/models/converters/mod.rs, src/models/converters/tests/data_decoded.rs, src/models/converters/tests/mod.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/tests/summary.rs, src/models/service/transactions/mod.rs, src/utils/mod.rs
=> Closes #110 Include SettingsInfo in SettingsChange variant of TransactionInfo

src/models/backend/transactions.rs, src/models/converters/transactions/details.rs, src/models/converters/transactions/tests/details.rs, src/models/converters/transactions/tests/transfer_type_checks.rs, src/models/service/transactions/details.rs
Closes #115 
- Added optionally present `submission_date`
=> Closes #115 confirmation submission date

src/models/service/transactions/mod.rs
Closes #118 
- Enum type SCREAMING_SNAKE case
- fields camelCase
=> Closes #118

src/config/mod.rs, src/json/balances/balance_compound_ether.json, src/json/balances/balance_ether.json, src/json/mod.rs, src/models/backend/balances.rs, src/models/backend/mod.rs, src/models/converters/balances.rs, src/models/converters/mod.rs, src/models/converters/tests/balances.rs, src/models/converters/tests/mod.rs, src/models/service/balances.rs, src/models/service/mod.rs, src/providers/info.rs, src/routes/balances.rs, src/routes/mod.rs, src/services/balances.rs, src/services/mod.rs
Closes #133
- Added endpoint `/v1/safes/<address>/balances/<fiat>/`
- Introduced new `struct` for both backend and service
- Introduced method for fetching exchanged rated from the [ECB](https://exchangeratesapi.io/)
Pending
- ~~Better implementation for exchange rate fetching in the `DefaultInfoProvider`~~
- ~~Tests for converters~~
- ~~Maybe it is time to add tests for the `DefaultInfoProvider`~~ #159
=> Closes # 133 Eur and Usd fiat balances

src/routes/balances.rs, src/services/balances.rs
Closes #163 
Changes:
- Added `trusted` and `exclude_spam` filters, both with `false` default value
=> "trusted" and "exclude_spam" filters added to balance endpoint

src/routes/balances.rs
=> Change exclude_spam filter default value to true

Cargo.lock, Cargo.toml
=> Version bump to 1.5.0

src/models/converters/balances.rs, src/models/converters/tests/balances.rs
=> Changed default value to 18 for ETH

Cargo.toml, src/main.rs, src/monitoring/mod.rs, src/monitoring/performance.rs
- Add status code to monitorin
- Bump version to 1.5.1
=> Monitoring status code

Cargo.toml
=> 1.5.2 version bump

src/routes/about.rs, src/routes/collectibles.rs, src/services/transactions_details.rs
Closes #219 
- Added trailing slash to core serivces request URLs
=> Added trailing slash to URLs for requests to the core services

src/services/tests/transactions_history.rs, src/services/transactions_history.rs
Closes #225 
- `timezone_offset` sent by the clients is used to adjust the calculation of date labels
- Added tests for UTC +1:00 and UTC+11:00
=> Consumption of timezone offset and adjustment of datelabels

src/routes/mod.rs
Closes #222 
- Added redirect to wiki in the root path
=> Added root redirect to github wiki docs

.travis.yml, Cargo.lock, Cargo.toml
=> Version bump v1.7.0

.github/workflows/rust.yml
Adding project checkout for deployment step
=> Fix deployments

scripts/deploy_docker.sh
=> Fixed path to Dockerfile in the deployment script

.github/workflows/rust.yml, scripts/deploy_docker.sh
Changes:
- Restored to prior deployment script
- Adjusted variables to obtain the info from github action's env
=> Restored deployment script and adjusted to use GitHub env

Cargo.lock, Cargo.toml
=> Version bump v1.8.1

.env.sample, src/services/transactions_history.rs
=> Added documentation for the filtering logs better

src/config/mod.rs, src/routes/balances.rs, src/services/balances.rs
=> Added 60 seconds timeout for balances endpoint

Cargo.lock, Cargo.toml, src/providers/info.rs
Closes #300 
Changes:
- TokenInfo correct timeout
=> Used correct timeout

src/config/mod.rs, src/providers/info.rs, src/routes/about.rs, src/routes/hooks.rs, src/routes/mod.rs, src/services/tests/invalidate_caches.rs, src/utils/cache.rs
=> Used correct invalidation patterns

add_rustfmt_git_hook.sh, src/utils/tests/urls.rs, src/utils/urls.rs
- Handle missing trailing slash
- Remove query params if present
=> Fix building manifest url

src/utils/cache.rs
=> Fixed redis command

Cargo.lock, Cargo.toml, src/services/transactions_queued.rs
Closes #249 
- Added `submissionDate` sorting
=> Added sorting by submissionDate but seemingly no change

src/services/balances.rs
Closes #318 
https://stackoverflow.com/a/60916195/7721253 => Benchmark of possible ways to solve this
Sorting by fiat balance for the `balances` endpoint.
=> Added sort by fiat balance to endpoint

Cargo.toml, src/config/mod.rs, src/providers/info.rs, src/utils/cache.rs
=> Added timeout and error caching

Cargo.lock, src/macros.rs, src/models/converters/transactions/tests/details.rs, src/providers/info.rs, src/services/transactions_details.rs
Closes #298 
Changes:
- new `client_error!` macros for easy early returns
=> 422 for unsupported currencies

Cargo.lock, src/config/mod.rs, src/models/converters/balances.rs
Closes #179 
Changes:
- Added `NATIVE_COIN_NAME`, `NATIVE_COIN_SYMBOL` and `NATIVE_COIN_DECIMALS` for balances
- **caveat:**  there is still `TokenType::Ether`
=> Added env for native coin

src/json/transactions/multisig_cancellation_transaction.json, src/models/converters/transactions/mod.rs, src/models/converters/transactions/tests/is_cancellation.rs
=> Require safeTxGas to be 0 for cancellations

.env.sample
Closes #319 
- Updated `.env.sample`
Note: I will update the wiki as well
=> Updated .env.sample for completion

src/providers/info.rs, src/services/balances.rs
=> USD fiat skip check against exchange API

.github/workflows/rust.yml, scripts/deploy_docker.sh
- Add branch filter for `spectrum`
- Enable docker image caching for `spectrum`
=> Add spectrum to CI pipeline

src/models/converters/data_decoded.rs, src/models/converters/mod.rs, src/models/converters/safes.rs, src/models/converters/transactions/details.rs, src/models/converters/transactions/mod.rs, src/models/converters/transactions/safe_app_info.rs, src/models/converters/transactions/summary.rs, src/models/converters/transfers.rs, src/providers/ext.rs, src/providers/mod.rs, src/services/transactions_list.rs, src/utils/context.rs, src/utils/mod.rs, src/utils/tests/errors.rs
Closes #350 
- Removed mutability of `InfoProvider`
- Inlined functions that were extracted from closures previously
=> `InfoProvider` no longer mutable. Restored closures

src/services/transactions_details.rs
Closes #355 
Changes:
- We return 422s now for bad ids
=> Changed response code for bad ids in tx details

src/utils/errors.rs
Closes #366 
Changes:
- More defensive error forwarding
=> Added more defensive error forwarding

Cargo.lock, Cargo.toml, src/models/service/safes.rs, src/services/safes.rs
=> Service Poll: Safe endpoint to include timestamps

src/models/converters/tests/data_decoded.rs, src/models/converters/tests/transfers.rs, src/models/converters/transactions/details.rs, src/models/converters/transactions/tests/details.rs, src/models/converters/transfers.rs, src/models/service/transactions/details.rs
Closes #373 
- Moved `address_info_index` from `tx_details` to `tx_data`
=> Moved `address_info_index` to `tx_data` as according to spec

README.md
- Update path of the requirements.txt file in the Tests section of README
=> Update Tests section of README.md

Cargo.lock, Cargo.toml
Closes #394 
Changes:
- Cargo version bumped to `2.0.0`
- Included @fmrsabino as a project author
=> Version bumped and added Frederico as author

Cargo.lock, Cargo.toml
=> Bumped version to v2.0.1

.github/workflows/rust.yml, src/routes/mod.rs
=> Fixed internal documentation links

.github/workflows/rust.yml, scripts/deploy_docker.sh
Closes #427 
Changes:
- Added step for `interstellar` deployment in GH action script
- Added branch for `interstellar` for `deploy_docker.sh`
=> Adjusted GH action and deployment script for `Interstellar`

src/models/service/mod.rs, src/models/service/utils.rs, src/routes/about.rs, src/routes/mod.rs, src/routes/utils.rs, src/services/mod.rs, src/services/utils.rs
Closes #423 
Changes:
- Added `data_decoder` endpoint
- Added `gas_estimation` endpoint
- Added `master_copies` endpoint
=> Forward endpoints

src/models/chains.rs, src/models/tests/chains.rs, src/models/tests/commons.rs, src/models/tests/mod.rs, src/services/tests/backend_url.rs
Closes #443 
- Add theme payload to `ChainInfo`
- The theme payload includes `textColor` and `backgroundColor`
=> Add theme payload to ChainInfo

src/routes/about.rs, src/services/balances.rs
=> Fixed master-copies endpoint

src/models/chains.rs, src/models/converters/tests/balances.rs, src/models/tests/chains.rs, src/services/balances.rs, src/services/tests/backend_url.rs
Closes #461 
- Consume and expose the `logo_url` from the config service to the clients
=> Add currency logo field to ChainInfo

.github/workflows/rust.yml
=> Fix docker deploys

.github/workflows/rust.yml
Changes:
- ~~Added `&&` to multi-command multi-line `run` statement~~
- Did it like in the docs
=> Added missing operator

src/macros.rs, src/providers/info.rs, src/services/chains.rs
Closes #441 
Change:
- For sake of simplicity and control, went with the `format!` approach
- To hide implementation, added `config_uri!` macro, to match `core_uri!`
=> Added `config_uri!` macro

src/json/chains/rinkeby_fixed_gas_price.json, src/json/chains/rinkeby_unknown_gas_price.json, src/json/mod.rs, src/models/backend/chains.rs, src/models/converters/chains.rs, src/models/service/chains.rs, src/models/tests/chains.rs, src/services/tests/backend_url.rs
Closes #444 
- Add Gas Price to `ChainInfo`
=> Add Gas Price to /v1/chains/<chain_id>

src/providers/info.rs
=> In-memory cache for `ChainInfo`

src/models/converters/transactions/summary.rs, src/models/converters/transactions/tests/summary.rs, src/models/service/transactions/summary.rs, src/services/tests/transactions_history.rs, src/services/tests/transactions_queued.rs
Closes #487: Add execution info for module transactions
=> Closes #487: Add execution info for module transactions

src/models/converters/page_metadata.rs, src/models/converters/tests/page_metadata.rs, src/routes/transactions.rs, src/services/transactions_history.rs, src/services/transactions_queued.rs
=> Renamed query parameter `page_url` to `cursor`

src/models/backend/mod.rs, src/models/backend/safes.rs, src/models/converters/safes.rs, src/models/converters/tests/safes.rs, src/providers/info.rs, src/routes/about.rs, src/services/about.rs, src/services/safes.rs
=> Enhancing logic for `Up-to-Date` implementation version

src/json/chains/rinkeby.json, src/json/chains/rinkeby_rpc_auth_unknown.json, src/json/chains/rinkeby_rpc_no_auth.json, src/json/chains/rinkeby_unknown_gas_price.json, src/json/mod.rs, src/models/backend/chains.rs, src/models/converters/chains.rs, src/models/service/chains.rs, src/models/tests/chains.rs, src/services/tests/backend_url.rs
Closes #507 
- Add the authentication type payload and expose it to the clients
=> Add RPC authentication payload

src/cache/cache_operations.rs, src/cache/tests/cache_operations.rs, src/providers/info.rs
=> Made `TokenInfo` caching network dependent

src/models/backend/safes.rs, src/models/converters/safes.rs, src/models/converters/tests/safes.rs, src/models/service/safes.rs, src/services/about.rs
=> Expose only `address` and `version` in `/about/master-copies` endpoint

.github/workflows/rust.yml
=> Preparing deployment scripts

src/models/service/about.rs, src/models/service/transactions/details.rs, src/models/service/transactions/summary.rs, src/routes/about.rs
Closes #500 
Modified examples to highlight changes in the API
=> Updated docs to reflect changes in the API

src/json/chains/rinkeby.json, src/json/chains/rinkeby_fixed_gas_price.json, src/json/chains/rinkeby_rpc_auth_unknown.json, src/json/chains/rinkeby_rpc_no_auth.json, src/json/chains/rinkeby_unknown_gas_price.json, src/models/backend/chains.rs, src/models/converters/chains.rs, src/models/service/chains.rs, src/models/tests/chains.rs, src/services/tests/backend_url.rs
Closes #515 
- Add support for serialising and deserialising Block Explorer URI templates from the config service API
=> Add Block Explorer URI templates

.env.sample, README.md
=> Removed confusing parts of the `.env.sample` and `README` files

src/macros.rs, src/models/backend/transactions.rs, src/models/service/utils.rs, src/services/utils.rs
Closes #485 
We default nonce to `0` when there is no multisigTx available (which shouldn't happen)
=> Latest nonce

.env.sample, src/config/mod.rs, src/models/commons.rs, src/routes/mod.rs, src/routes/safes.rs, src/services/safes.rs
Closes #529 
Cache both response and request to backend service for 1 minute as agreed
=> Forwared endpoint to `/owners/{address}/safes`

src/models/service/transactions/requests.rs
=> Skipping null fields for tx proposal request

src/utils/errors.rs
=> Added 504 status code for backend timeout errors

Cargo.lock, Cargo.toml
=> Removed cargo watch as a project dependency

src/routes/transactions.rs
=> Returning transaction details after proposing tx

Cargo.lock, Cargo.toml, src/services/transactions_proposal.rs
=> Added `safe_tx_hash` invalidation for `propose` tx

src/services/transactions_proposal.rs
Closes #603 
Other `post` requests had a timeout. 
`default_request_timeout()` is `10000` milliseconds
=> Added time out to `post` requests

Cargo.lock, Cargo.toml
=> Version bump to v3.3.0

src/json/chains/rinkeby.json, src/json/chains/rinkeby_fixed_gas_price.json, src/json/chains/rinkeby_multiple_gas_price.json, src/json/chains/rinkeby_no_gas_price.json, src/json/chains/rinkeby_rpc_auth_unknown.json, src/json/chains/rinkeby_rpc_no_auth.json, src/json/chains/rinkeby_unknown_gas_price.json, src/models/backend/chains.rs, src/models/converters/chains.rs, src/models/service/chains.rs, src/models/tests/chains.rs, src/services/tests/backend_url.rs
Closes #615 
- Adds `l2` field to `ChainInfo` (both backend and client models)
=> Add L2 field to ChainInfo

src/services/safes.rs
Closes #604 
Looking for more places where this can be implemented
=> using join! to parallelise request in safe_info endpoint

src/json/chains/rinkeby.json, src/json/chains/rinkeby_fixed_gas_price.json, src/json/chains/rinkeby_multiple_gas_price.json, src/json/chains/rinkeby_no_gas_price.json, src/json/chains/rinkeby_rpc_auth_unknown.json, src/json/chains/rinkeby_rpc_no_auth.json, src/json/chains/rinkeby_unknown_gas_price.json, src/models/backend/chains.rs, src/models/converters/chains.rs, src/models/service/chains.rs, src/models/tests/chains.rs, src/services/tests/backend_url.rs
- Adds `description` field to `ChainInfo` (both backend and client models)
=> Add description field to Chain

src/json/results/tx_details_with_origin.json, src/models/converters/transactions/details.rs, src/models/converters/transactions/tests/details.rs, src/models/service/transactions/details.rs
Closes #543 
The web team needs to be notified when this is deployed to staging (before we merge)
=> Changed `baseGas` and `safeTxGas` types to `String`

docker-compose.yml
Fixed some variable issues and facilitated localhost exposure with more explicit env values
=> Fixed env var name in the docker-compose.yml file

.env.sample, src/config/mod.rs, src/json/mod.rs, src/json/safe_apps/polygon_safe_apps.json, src/models/backend/mod.rs, src/models/backend/safe_app.rs, src/models/converters/mod.rs, src/models/converters/safe_app.rs, src/models/converters/tests/mod.rs, src/models/converters/tests/safe_app.rs, src/models/service/mod.rs, src/models/service/safe_app.rs, src/routes/mod.rs, src/routes/safe_apps.rs, src/services/mod.rs, src/services/safe_apps.rs
=> `/safe-apps` forwarding endpoint

src/utils/cors.rs
Closes #623 
https://github.com/lawliet89/rocket_cors/blob/master/src/fairing.rs#L90-L98
=> 204 status code forced for a pre-flight OPTION requests

src/providers/info.rs, src/routes/about/tests/routes.rs, src/routes/transactions/handlers/proposal.rs
=> Generated json correctly for `Confirmation` POST request

src/cache/cache_op_executors.rs, src/routes/collectibles/mod.rs, src/routes/collectibles/tests/mod.rs, src/routes/collectibles/tests/routes.rs, src/routes/contracts/mod.rs, src/routes/contracts/tests/mod.rs, src/routes/contracts/tests/routes.rs, src/tests/json/collectibles/collectibles_page.json, src/tests/json/commons/data_decoded_approve.json, src/tests/json/mod.rs
=> Coverage for `collectibles` an `contracts` modules

.github/workflows/cla.yml
- Use the newer `cla-assistant` version instead of `gnosis/cla-github-action`
=> Use cla-assistant/github-action

src/main.rs, src/providers/address_info.rs, src/providers/info.rs, src/providers/mod.rs, src/providers/tests/info.rs, src/routes/contracts/handlers.rs, src/routes/contracts/routes.rs, src/routes/contracts/tests/routes.rs, src/routes/mod.rs, src/tests/json/contracts/contract_info_BID.json, src/tests/json/mod.rs
=> exposing `ContractInfo` in an endpoint

src/routes/health/mod.rs, src/routes/health/tests/mod.rs, src/routes/health/tests/routes.rs, src/routes/notifications/handlers.rs, src/routes/notifications/mod.rs, src/routes/notifications/models.rs, src/routes/notifications/tests/mod.rs, src/routes/notifications/tests/routes.rs, src/routes/safe_apps/mod.rs, src/routes/safe_apps/models.rs, src/routes/safe_apps/tests/json/response_safe_apps.json, src/routes/safe_apps/tests/mod.rs, src/routes/safe_apps/tests/routes.rs, src/utils/errors.rs
Closes #730 
Added unit tests for endpoints:
- `/health` 
- `DELETE notifications` and `POST notifications`
- `/safe-apps`
=> Tests for `health`, `notifications` and `safe_apps` endpoints

src/common/models/addresses.rs, src/routes/transactions/converters/details.rs, src/routes/transactions/converters/tests/details.rs, src/routes/transactions/tests/json/post_confirmation_result.json
=> `txData::to` request full address search for contract/token info

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Updated issue and feature request templates

src/routes/safes/handlers/estimations.rs, src/routes/safes/tests/json/last_history_tx.json, src/routes/safes/tests/routes.rs
Closes #753: Ensure latest nonce is not too low
=> Closes #753: Ensure latest nonce is not too low

src/providers/address_info.rs, src/routes/transactions/converters/details.rs, src/routes/transactions/converters/tests/details.rs, src/tests/json/contracts/contract_info_BID.json
=> Maded `trustedForDelegateCall` from core services not nullable

Cargo.lock, Cargo.toml, scripts/deploy_docker.sh
Release: https://github.com/safe-global/safe-client-gateway/releases/tag/v3.52.0
=> Backmerge release 3.52.0
