- src/models/backend/transactions.rs
- src/models/commons.rs
- src/models/converters/transactions.rs
- src/models/service/transactions.rs
- src/routes.rs
- src/routes/transactions.rs
- src/services.rs
- src/services/transactions.rs
- Added `/transactions/{safe_id}` endpoint forwarding to `/safe/{safe_id}/all-transactions`
- Pointing transaction backend to staging/rinkeby
- Added field to mapping method and made everything option for objects coming from the transaction service
> Include Transaction type field

- src/cache.rs
- src/config/mod.rs
- src/main.rs
- src/providers/info.rs
- src/providers/mod.rs
- src/routes/transactions.rs
- src/services.rs
- src/services/transactions.rs
- src/utils.rs
- src/utils/context.rs
- src/utils/cors.rs
Closes #29: Add provider to load token info
Closes #28: Add provider to load safe info
- Added redis cache
- Added in-memory cache that is used while processing one request
- Added config module
- Added context request guard for easy access to shared client and cache wrapper
> Closes #29 and Closes #28: Add info provider for safes and tokens

- src/models/backend/transfers.rs
- src/models/converters/transactions.rs
- src/models/converters/transfers.rs
- src/models/service/transactions.rs
Closes #36
- Made certain fields nullable when token info is not found in the backend's token endpoint
> Closes #36 fix for missing token info

- src/models/converters/transactions.rs
- src/models/converters/transfers.rs
- src/models/service/transactions.rs
Closes #45 
- Fields for `TransferInfo` are now camelCased
- Status enum no longer changed
> Closes #45 Corrected casing for fields in transfers and status enum

- src/config/mod.rs
- src/models/service/about.rs
- src/routes/transactions.rs
- src/services/about.rs
Closes #41 
Changes:
- Added json structure: 
```rust
pub struct About {
pub transaction_service_base_url: String, // base url defined in .env file
pub name: String, // crate name
pub version: String, // crate version
pub transaction_service_version: Option<String>, // version returned by about endpoint of transaction service
pub build_number: Option<String>, //commit count of master
} 
```
> Closes #41: About endpoint

- src/macros.rs
- src/main.rs
- src/models/backend/transactions.rs
- src/models/converters/transactions/mod.rs
- src/models/converters/transactions/summary.rs
- src/models/converters/transactions/tests/mod.rs
- src/models/converters/transactions/tests/summary.rs
- src/models/service/transactions/mod.rs
- src/services/mod.rs
- src/services/tests/mod.rs
- src/services/tests/transaction_list.rs
- src/services/transactions_details.rs
- src/services/transactions_list.rs
Closes #56 
Changes:
- Added `CreationTransaction` for backend deserialisable types
- Added `Creation` concretization of `TransactionInfo` for `TransactionSummary`
- Cached results
- Improved test structure and added test for mapping
- Moved macros to root of the crate because of visibility issues in other modules
> Closes #56 Creation transaction

- src/services/transactions_details.rs
Closes #74 
- Else branch for resolving ID uses whatever is passed in the path as `SafeTxHash`
Not very elegant...
> Closes #74 Safe TX hash usable for TX Details endpoint

- src/models/converters/transactions/details.rs
- src/models/converters/transactions/tests/details.rs
- src/models/service/transactions/details.rs
Closes #95 
- Included the `executor` field in the `MultisigExecutionDetails` object response
- Added to test
> Closes #95 Include executor in MultisigExecutionDetails

- src/models/converters/transactions/summary.rs
- src/models/converters/transactions/tests/summary.rs
- src/services/transactions_details.rs
Closes #96 
- Replaced `block_number` for `transaction_hash` for filtering TX details results
- Fixed tests accordingly.
> Closes #96 use TX Hash instead of block number for filtering TX details results

- src/providers/info.rs
- src/utils/cache.rs
Closes #90
- We already store in redis if the response errored
- Added this to in-memory cache with an Option
We should improve how `request_cached` works:
- Only cache on success (or add a flag to specify this)
- Return reqwest error to caller so that they can react to it if necessary
- This could be partially handled in https://github.com/gnosis/safe-client-gateway/issues/54 and if we see more changes necessary we create a follow up issue
> Closes #90: Cache in-memory if no token info could be found

- src/models/converters/transactions/summary.rs
- src/models/converters/transactions/tests/summary.rs
- src/models/service/transactions/mod.rs
- src/routes/transactions.rs
- src/services/transactions_list.rs
Closes #107
- Rename `master_copy` in creation to `implementation` 
- Rename `next` in transcations endpoint to `page_url`
> Closes #107: Rename params

- src/routes/hooks.rs
- src/services/hooks.rs
Closes #124 
- Invalidate cache with `safe_tx_hash` for new confirmations, for execution of multisig transactions and new pending multisig transactions
Created #125 for tests
> Closes #124 : Invalidate cache with safe tx hash if possible

- src/models/converters/transactions/summary.rs
- src/models/converters/transactions/tests/summary.rs
- src/services/transactions_details.rs
Closes #124 
- Included `SafeAddress` as part of the id for MultisigTransactions for cache invalidation
> Closes #124 Included safe address in multisig tx Id

- src/models/converters/transactions/details.rs
- src/models/converters/transactions/tests/details.rs
- src/models/service/transactions/details.rs
- src/providers/info.rs
Closes #53 
- Added fields for signing transactions (in the required order) as part of the `MultsigExecutionDetails`
- Adding gas token info optionally, when available
> Closes #53 Fields for sign submission

- src/models/converters/transactions/mod.rs
- src/models/converters/transactions/tests/details.rs
- src/models/converters/transactions/tests/summary.rs
- src/models/service/transactions/mod.rs
Closes #114 
- Including `data_decoded` in Custom `TransactionInfo` to have access to method name and params
> Closes #114 Method name for custom transactions in summary

- Cargo.lock
- Cargo.toml
- src/routes/about.rs
- src/routes/transactions.rs
- src/services/about.rs
- src/services/tests/invalidate_caches.rs
- src/services/transactions_details.rs
- src/services/transactions_list.rs
- src/utils/cache.rs
- src/utils/errors.rs
- src/utils/mod.rs
- src/utils/tests/cache.rs
- src/utils/tests/errors.rs
- src/utils/tests/mod.rs
Closes #54 
- Added `ApiResult` type alias with type wrappers for most common errors
- Tests 
- Added polymorphic `message` field
- Attempted deserialisation of the backend error
- client errors are cached
> Closes #54 Better error handling

- src/providers/info.rs
- src/utils/json.rs
- src/utils/mod.rs
- src/utils/tests/json.rs
- src/utils/tests/mod.rs
Closes #142
- Default on null value deserialiser added to JSON utils
- Any other default value required for a specific type can be add by implementing the `Default` trait for said type
> Closes #142 Null decimals in TokenInfo handled

- src/routes/health.rs
- src/routes/mod.rs
- src/utils/cache.rs
Closes #127 
- ~~Health endpoint caches the response from `/about` endpoint of the transaction service and returns it~~
- Health endpoint caches and responds with the value from the`("/health", "")` key value pair
> Closes #127 Introduction of health endpoint

- Cargo.lock
- Cargo.toml
Set version number to 1.2.0
This does not affect the version number returned by the `about` endpoint as this one is based on the GitHub tag.
> Closes #153: Update version number

- src/main.rs
- src/monitoring/mod.rs
- src/monitoring/request_timer.rs
Closes #147 
- Using request's `local_cache` to store the timestamp of when the request was received
> Perf logs 

- src/models/converters/transactions/tests/mod.rs
- src/services/transactions_details.rs
Closes #165 
- Changed endpoint for multisig tx details endpoint to `/multisig-transactions`
- restored missing `details` test module causing the test coverage crash (partly)
> Update /transactions to /multisig-transactions backend endpoint 

- .travis.yml
- Cargo.lock
- Cargo.toml
Closes #173 
Note: the build process was interrupted because `rustfmt` was not available for the latest nightly build. There where 2 possible solutions for the problem:
- Add `--allow-downgrade` as described [here](https://github.com/actions-rs/toolchain/issues/53#issuecomment-603244046)
- Nightly version pinning. This has the added advantage of locking versions like it is done for dependencies. Any future potentially breaking changes are not used. For reference look at [this](https://github.com/travis-ci/travis-ci/issues/7167#issuecomment-405799816) and [this](https://github.com/crate-ci/example-clippy/blob/master/.travis.yml#L12)
> Version bump for 1.4.0

- src/models/service/balances.rs
- src/services/balances.rs
Closes #175 
- Included `fiat_total` in the root of the response object
- All the individual balances are included now under `items`
> Included the fiat total as part of the balance response

- src/monitoring/request_timer.rs
- Closes #191
- [x ] You are using the nightly version of rust `rustup default nighly`
- [x ] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [x ] You ran `cargo fmt` on the code base before submitting
> Adjust logging format for fluentd

- src/routes/collectibles.rs
Closes #207 
- Added `trusted` and `exclude_spam` filters
- Set `exclude_spam` to `true` and left `trusted` to default to the same value in the core services swagger (`false`)
> Added trusted and exclude_spam filter flags for forwarding

- src/models/service/transactions/summary.rs
- src/services/tests/transactions_history.rs
- src/services/transactions_history.rs
- src/services/transactions_queued.rs
- `tx_item_type` renamed to `type`
- Variants are capitalised under `type`
> Casing issues for History and Queued endpoints

- src/providers/info.rs
- src/routes/balances.rs
- src/routes/mod.rs
Closes #212 
- Endpoint `/v1/balances/supported-fiat-codes`
- Extracted method for `DefaultInfoProvider`
> Added an endpoint returning  all supported fiat codes

- src/services/transactions_history.rs
Closes #210 
- Fetching only executed transactions for the `all-transactions` endpoint
> Filtered only transactions that aren't queued and were in fact executed

- src/services/tests/transactions_history.rs
- src/services/transactions_history.rs
Closes #232 
- Added unit test for negative timezones
- Return the date label with the timestamp adjusted to the device's timezone
> Added timezone offset correction for correct date label placement

- src/json/balances/balance_compound_ether.json
- src/json/balances/balance_ether.json
- [x ] You are using the nightly version of rust `rustup default nighly`
- [x ] You have the latest version of `rustfmt` installed
```bash
$ rustup component add rustfmt
```
- [x ] You ran `cargo fmt` on the code base before submitting
> Remove usd naming from core services

- src/utils/errors.rs
Closes #197 
Changes:
- `Responder` impl for `ApiError` logs the error too. Example output:
`[2021-02-09T13:23:21Z ERROR safe_client_gateway::utils::errors] ERR::500::/about::ApiErrorMessage: code:1337; message:Some("Error(\"missing field `transactionServiceBaseUrl`\", line: 1, column: 29)"); arguments:None`
- To disable rocket logs we should set `.env::ROCKET_LOG = off`
> Added error logging

- src/models/service/transactions/mod.rs
Closes #262 
Enforce camelCasing for returned `SettingsInfo` objects
> Added camel correction for SettingsInfo objects

- src/models/converters/transactions/tests/is_cancellation.rs
- src/models/converters/transactions/tests/mod.rs
Closes #264 
Changes:
- Added tests to branching paths for cancellations
- Updated the documentation to display a cancellation tx example: https://github.com/gnosis/safe-client-gateway/wiki/transactions_proposal#json
> Added tests for is_cancellation method

- src/models/backend/transactions.rs
- src/models/converters/transactions/tests/summary.rs
Closes #271 
Changes:
- Removed `to` as expected field from Ethereum transactions as it's not used.
> Removed to field from ethereum transactions

- Cargo.lock
- Cargo.toml
- add_rustfmt_git_hook.sh
- src/config/mod.rs
- src/main.rs
- Adds connect timeout to internal client
- Should be properly followed up on (https://github.com/gnosis/safe-client-gateway/issues/275)
> Add connect timeout to internal client

- src/config/mod.rs
- src/providers/info.rs
- src/routes/collectibles.rs
- src/services/balances.rs
- src/services/transactions_details.rs
- src/services/transactions_history.rs
- src/services/transactions_list.rs
- src/services/transactions_queued.rs
- src/utils/cache.rs
Closes #246 
Changes:
- Added `REQS_ERROR_CACHE_DURATION` and `INFO_ERROR_CACHE_DURATION` env vars
- Default is 1 minute and 24 hours respectively
- Only 4xx errors are cached (old behaviour is preserved)
> Info and Request error cache timeout added

- Cargo.lock
- Cargo.toml
- src/providers/info.rs
- src/services/hooks.rs
- src/services/tests/invalidate_caches.rs
- src/utils/cache.rs
This PR just shows what changes are required to load all tokens at once into the cache. This will allow us to run some tests on the performace impact.
Findings:
- Lots of small requests to core services result in quite some overhead right now
- Keep Alive does not solve this
- Http2 is not available for services right now (we are coordinating with devops to evaluate this)
- Request for unknown addresses that don't hit a known token take longer
- Information is pulled from on-chain (@Uxio0 maybe we could add a query param, that disables the on-chain lookup?)
- Using `/v1/tokens/?limit=10000` to load all tokens into cache provides improvements
- Cold load request time goes down by 50% (~15s to ~8s) - Note: I did NOT do extensive benchmarking 
- Uses ~1.5mb of redis cache (not really an …
> Warm up cache with TokenInfo

- src/config/mod.rs
- src/providers/info.rs
Closes #278 
Overhauled cache durations according to https://github.com/gnosis/safe-client-gateway/issues/278#issuecomment-786650720
Remaining TODO's: 
- Notify devOps about deprecation of `INFO_CACHE_DURATION`
> Overhauled cache durations

- Cargo.lock
- Cargo.toml
- src/macros.rs
- src/models/converters/transactions/details.rs
- src/models/converters/transactions/mod.rs
- src/models/converters/transactions/tests/details.rs
- src/models/service/transactions/details.rs
- src/services/transactions_details.rs
- src/utils/mod.rs
- src/utils/tests/mod.rs
- src/utils/tests/transactions.rs
- src/utils/transactions.rs
Closes #258 
Changes:
- `MultisigExecutionDetails` now include a list of `rejectors`
- `SafeTxHash` calculation exclussively for cancellation works (Tests assume `safe_tx_gas == 0`, therefore test data generated with the current web app will not match the resulting hash)
- Made extensive use of `ethabi::encode` where possible (ERC191 bytes were padded when added there, so they had to be pushed directly into the vector, is this what encoded `packed` would have solved?)
- Added `to_hex_string` macro, I would like add `to_checksummed_hex_string` at some point. WDYT, @rmeissner ?
> Rejection list for transactions

- src/routes/mod.rs
- src/routes/transactions.rs
- src/utils/errors.rs
Closes #277 
Changes:
- Added error catcher for 422s
Note: It seems like rocket has built-in helpful error catchers that trigger the behaviour reported by Dirk: https://api.rocket.rs/v0.4/rocket/struct.Catcher.html#built-in-catchers
Do we add more catchers for common and expected error codes? For now I just covered the one that Dirk encountered.
> Added a catcher for 422s

- src/models/converters/transactions/summary.rs
- src/models/converters/transactions/tests/summary.rs
- src/models/service/transactions/mod.rs
- src/services/transactions_list.rs
Closes #245 
Changes:
- Added `creator_info`, `factory_info` and `implementation_info` fields of `AddressInfo` type
- Unit tests
> Added AddressInfo fields to CreationTransaction

- Cargo.lock
- Cargo.toml
- src/config/mod.rs
- src/utils/cache.rs
- Allow to set the count for scan -> new `scan_match_count` function. 
- Introduce env variable for scan count -> `REDIS_SCAN_COUNT` (default `300`)
More info https://docs.keydb.dev/blog/2020/08/10/blog-post/
> Use custom scan count

- src/models/converters/transactions/details.rs
- src/models/converters/transactions/tests/details.rs
- src/models/service/transactions/details.rs
Closes #310 
- Renamed `rejections` to `rejectors`
> Renamed field

- src/routes/balances.rs
- src/services/balances.rs
Closes #314 
- Sorted fiat codes returned by `/v1/balances/supported-fiat-codes` as USD, EUR and rest in alphabetical order
> Sorted fiat codes according to spec: USD, EUR, rest in alphabetical order

- src/models/converters/transactions/safe_app_info.rs
- src/models/converters/transactions/tests/safe_app_info.rs
closes #224 
- Replace `ipfs.io` with `cloudflare-ipfs.com` in the url
> Cloudflare ipfs node used instead of default for safe apps

- src/cache/cache_op_executors.rs
- src/cache/cache_operations.rs
- src/routes/hooks.rs
- src/routes/mod.rs
Closes #354 
Changes:
- Introduced `/v1/flush_tokens/<webhook_token>` endpoint
- Introduced `Tokens` variant as an invalidation pattern
> Added Tokens variant to invalidation patterns

- src/services/safes.rs
Closes #370 
- Added filter for only NFTs
> ERC721 filter for `collectibleTag` field in the `/v1/safes/<address>` endpoint

- Dockerfile
- scripts/deploy_docker.sh
Based on https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/
Note: there will be an error that the `builder` image is not available the first time we run this, but this is only a "soft" error an everything will still work.
More context:
We currently have multiple "base" images: `develop`, `main`, `spectrum` and `staging`. When building a version we were choosing between the different "base" images to reuse them for the docker cache source.
The 2 active "base" images in the client gateway repository are:
- `spectrum` used for the branch of the same name
- `staging` use for the latest commit of the `main` branch (and yes it is stupid that we also have a `main` "base" image, but something for another PR)
As we use …
> Try to better cache multi-stage docker build

- .env.sample
- Cargo.lock
- Cargo.toml
- src/config/mod.rs
- src/main.rs
- src/providers/info.rs
- src/utils/tests/transactions.rs
- src/utils/transactions.rs
Closes #348 
Changes:
- Added checking of safe version for calculating the `domain_separator`
- I still need to find real world data for `domain_hash_for_safe_address` test
> Domain separator for new safe version

- .github/workflows/rust.yml
- scripts/deploy_docker.sh
Closes #369 
Changes:
- Pinned version of grcov to `v0.8.0`
- Removed any `spectrum` associated branch in the deployment script
> Pinned `grcov` to v0.8.0

- src/utils/tests/transactions.rs
- src/utils/transactions.rs
Closes #399 
Changes:
- Moved down `get_chain_id` call, setting the `env` var in the test, thus validating the name
- Passed only the version for `use_legacy_domain_separator` method
> Refactor `safeTxHash` calculation

- src/cache/cache_op_executors.rs
> Passing `status_code` instead of hardcoded 42

- src/routes/chains.rs
- src/routes/mod.rs
Closes #422 
- Added a forward endpoint for `/v1/chains`
- Added an endpoint returning the `ChainInfo` of a single chain requiring the the `chain_id` as input
> Chain Endpoints

- src/config/mod.rs
- src/models/converters/balances.rs
- src/models/converters/tests/balances.rs
- src/services/balances.rs
Closes #436 
- Remove `native_coin_decimals`, `native_coin_symbol` and `native_coin_name`
- These functions were reading from the environment variables which no longer apply to the interstellar release
> Remove Native Coin config helpers

- src/routes/chains.rs
- src/services/chains.rs
- src/services/mod.rs
Closes #445
- `/v1/chains` now uses `ChainInfo` in order to parse and validate the returned payload by the Safe Config Service
> Use ChainInfo for pagination

- src/routes/about.rs
- src/routes/balances.rs
- src/routes/collectibles.rs
- src/routes/safes.rs
- src/routes/transactions.rs
- src/routes/utils.rs
Closes #457 
Changes: Endpoints follow the pattern `/v1/chains/<chaind_id>/...rest_of_the_old_endpoint`
> Normalise endpoints

- src/routes/chains.rs
- src/services/chains.rs
Closes #473
- The `limit` query parameter is now exposed to the clients so the default number of returned chains on a given page can be adjusted
> Expose limit query parameter for /chains

- src/models/backend/mod.rs
- src/models/backend/notifications.rs
- src/models/service/mod.rs
- src/models/service/notifications.rs
- src/routes/mod.rs
- src/routes/notifications.rs
- src/services/mod.rs
- src/services/notifications.rs
Closes #454 
Closes #455 
Changes:
- Added endpoints for registering and unregistering push notification 
- Introduced `structs` for backend request
- Introduced `struct` for gw request
> Register and Unregister push notification endpoints

- src/models/chains.rs
- src/models/tests/chains.rs
- src/services/tests/backend_url.rs
Closes #463
- Adds ENS registry address `ChainInfo` (optional field)
> Add ENS registry address to ChainInfo

- src/models/converters/balances.rs
- src/models/converters/tests/balances.rs
- src/models/converters/tests/transfer_ether.rs
- src/models/converters/tests/transfers.rs
- src/models/converters/transactions/mod.rs
- src/models/converters/transactions/tests/summary.rs
- src/models/converters/transactions/tests/transaction_types.rs
- src/models/converters/transactions/tests/transfer_type_checks.rs
- src/models/converters/transfers.rs
- src/models/service/transactions/mod.rs
- src/providers/info.rs
Closes #470 
Changes:
- renamed `TransferInfo::Ether`-> `TransferInfo::NativeCoin`
- renamed `EtherTransfer` -> `NativeCoinTransfer`
- renamed `TokenType::Ether` -> `TokenType::NativeCoin` 
- Fixed issue with `logo_uri` for native coins
> Renamed anything `Ether` to `NativeCoin`

- src/monitoring/mod.rs
- src/monitoring/performance.rs
- src/monitoring/tests/mod.rs
- src/monitoring/tests/path_patterns.rs
Closes #450 
Note: 
I can also include the query parameters for `request_path` if you like
We'd need to just add:
```rust
let request_params = request.uri().query();
log::error!("query params: {:#?}", request_params.as_ref().map(|it| it.to_string()));
```
> Adjusting logs for multiple chains

- src/macros.rs
- src/services/notifications.rs
Closes #476 
Current state:
The CGW responds with a status code `500` and the following body:
```json
{
"code": 1337,
"message": "Push notification registration failed for chain ids: 1, 4"
}
```
Where the `chain_id`s that failed are listed at the end of the `message` field
> Error forwading for notification endpoints

- src/macros.rs
- src/utils/tests/macros.rs
- src/utils/tests/mod.rs
Closes #489 
- Remove the extra `/` in the `config_uri` macro – the paths already include the initial slash.
> Fix config_uri macro uri formatting

- src/cache/cache_operations.rs
- src/cache/tests/cache_operations.rs
Closes #504 
Needs manual testing locally, only unit testing passing currently
> Adjusted `InvalidationPattern::Chains` to use config service base URL

- src/json/chains/rinkeby.json
- src/json/chains/rinkeby_fixed_gas_price.json
- src/json/chains/rinkeby_rpc_auth_unknown.json
- src/json/chains/rinkeby_rpc_no_auth.json
- src/json/chains/rinkeby_unknown_gas_price.json
- src/models/backend/chains.rs
- src/models/converters/chains.rs
- src/models/service/chains.rs
- src/models/tests/chains.rs
- src/services/tests/backend_url.rs
- Removes `blockExplorerUri` from both the config service and from the payload exposed to the clients since it is no longer required (after the introduction of `blockExplorerUriTemplate`)
> Remove blockExplorerUri from ChainInfo payload

- src/config/mod.rs
- src/providers/info.rs
> Added timeout for `ContractInfo` fetching

- .github/workflows/rust.yml
```bash
$ rustup component add rustfmt
```
> Added possibility to manually trigger this workflow

- docker-compose.yml
```bash
$ rustup component add rustfmt
```
> Fix REDIS_URL param in docker-compose.yml

- src/routes/chains.rs
Closes #565 
We no longer cache the response from the cgw. Given redis available glob-patterns for regex, we can't come with an effective pattern that solely matches `ChainInfo` related keys, without invalidating other keys by accident.
> Removed response caching for `ChainInfo` endpoints

- src/json/chains/rinkeby_fixed_gas_price.json
- src/json/chains/rinkeby_multiple_gas_price.json
- src/json/chains/rinkeby_no_gas_price.json
- src/json/chains/rinkeby_rpc_auth_unknown.json
- src/json/chains/rinkeby_rpc_no_auth.json
- src/json/chains/rinkeby_unknown_gas_price.json
- src/json/mod.rs
- src/models/backend/chains.rs
- src/models/converters/chains.rs
- src/models/service/chains.rs
- src/models/tests/chains.rs
- src/services/tests/backend_url.rs
Related with the following issue: https://github.com/gnosis/safe-config-service/issues/209
- The `config-service` now returns a collection of oracles (instead of a single oracle) so the deserialisation on the CGW side was adjusted. The payload exposed to the clients was also adjusted to reflect this new collection.
> Add support for multiple oracles per chain

- Cargo.toml
Sort dependencies in lexicographical order to improve readability and organisation of the dependencies that this project requires
> Sort dependencies lexicographically

- src/json/chains/rinkeby.json
- src/json/chains/rinkeby_fixed_gas_price.json
- src/json/chains/rinkeby_multiple_gas_price.json
- src/json/chains/rinkeby_no_gas_price.json
- src/json/chains/rinkeby_rpc_auth_unknown.json
- src/json/chains/rinkeby_rpc_no_auth.json
- src/json/chains/rinkeby_unknown_gas_price.json
- src/macros.rs
- src/models/backend/chains.rs
- src/models/tests/chains.rs
- src/services/tests/backend_url.rs
Closes #625 
Uses `vpcTransactionService` field within the `core_uri!` macro, but the field is not exposed to clients.
> Included `vpcTransactionService` in the struct `backend::ChainInfo`

- src/models/service/about.rs
- src/routes/about.rs
- src/routes/mod.rs
- src/services/about.rs
> Chainless `about` endpoint

- .env.sample
- .github/action-rs/grcov.yml
- .github/workflows/rust.yml
- src/config/mod.rs
- src/macros.rs
- src/services/tests/backend_url.rs
Closes #629 
Closes #631 
In addition to what @fmrsabino suggested, I introduced tests with debug assertion to also validate what is ran in the local setup unoptimized case.
However, after the discussion in the comments we have decided to stick to an implementation based on a environment variable, as this would allow better testability. 
Important note: From this PR onward tests would run in single thread, as changes to env vars behave non-deterministically in an async setup.
> Config flag to toggle between `vpcTransactionService` and `transactionService`

- src/common/models/backend/chains.rs
- src/routes/chains/converters.rs
- src/routes/chains/models.rs
- src/routes/chains/tests/chains.rs
- src/tests/backend_url.rs
- src/tests/json/chains/polygon.json
- src/tests/json/chains/rinkeby.json
- src/tests/json/chains/rinkeby_disabled_wallets.json
- src/tests/json/chains/rinkeby_fixed_gas_price.json
- src/tests/json/chains/rinkeby_no_gas_price.json
- src/tests/json/chains/rinkeby_rpc_auth_unknown.json
- src/tests/json/chains/rinkeby_rpc_no_auth.json
- src/tests/json/chains/rinkeby_unknown_gas_price.json
- src/tests/json/mod.rs
Closes #674 
- Adds `disabledWallets` field to `ChainInfo`
```javascript
GET /v1/chains/<chain_id>/
[
{
"chainId": <string>,
"disabledWallets": [<string>] // eg.: [ "metamask", "trust"]
...
}
]
```
> Add disabledWallets to ChainInfo

- src/common/models/backend/chains.rs
- src/routes/chains/converters.rs
- src/routes/chains/models.rs
- src/routes/chains/tests/chains.rs
- src/tests/backend_url.rs
- src/tests/json/chains/polygon.json
- src/tests/json/chains/rinkeby.json
- src/tests/json/chains/rinkeby_disabled_wallets.json
- src/tests/json/chains/rinkeby_fixed_gas_price.json
- src/tests/json/chains/rinkeby_multiple_gas_price.json
- src/tests/json/chains/rinkeby_no_gas_price.json
- src/tests/json/chains/rinkeby_rpc_auth_unknown.json
- src/tests/json/chains/rinkeby_rpc_no_auth.json
- src/tests/json/chains/rinkeby_unknown_gas_price.json
Closes #673 
- Adds `api` to `blockExplorerUriTemplate` in `ChainInfo`
```javascript
GET /v1/chains/<chain_id>/
{
"chainId": <string>,
"chainName": <string>,
"blockExplorerUriTemplate": {
"address": "https://etherscan.io/address/{{address}}", // example
"txHash": "https://etherscan.io/tx/{{txHash}}" // example
"api": "https://api.etherscan.io/api/?module={{module}}&action={{action}}&address={{address}}" // new field example
},
...
}
```
> Add Block Explorer API template to ChainInfo

- src/common/models/backend/chains.rs
- src/routes/chains/converters.rs
- src/routes/chains/models.rs
- src/routes/chains/tests/chains.rs
- src/tests/backend_url.rs
- src/tests/json/chains/polygon.json
- src/tests/json/chains/rinkeby.json
- src/tests/json/chains/rinkeby_disabled_wallets.json
- src/tests/json/chains/rinkeby_enabled_features.json
- src/tests/json/chains/rinkeby_fixed_gas_price.json
- src/tests/json/chains/rinkeby_multiple_gas_price.json
- src/tests/json/chains/rinkeby_rpc_auth_unknown.json
- src/tests/json/chains/rinkeby_rpc_no_auth.json
- src/tests/json/chains/rinkeby_unknown_gas_price.json
- src/tests/json/mod.rs
Closes #675 
- Add `features` to `ChainInfo`
```
GET /v1/chains/<chain_id>
{
"chainId": <string>,
"features": [<string>] // eg.: [ "ERC721", "SAFE_APPS"]
...
}
```
> Add Features to ChainInfo

- src/providers/info.rs
- src/providers/mod.rs
- src/providers/tests/info.rs
- src/providers/tests/mod.rs
- src/routes/transactions/converters/safe_app_info.rs
- src/routes/transactions/models/details.rs
- src/routes/transactions/models/summary.rs
- src/tests/json/mod.rs
- src/tests/json/safe_apps/uniswap_manifest.json
- src/utils/context.rs
Closes #689 
Tested coverage for:
- `TokenInfo`
- `SafeInfo`
- `SafeAppInfo`
- `ChainInfo`
> Improving test coverage for `InfoProvider`

- src/common/models/backend/chains.rs
- src/routes/chains/converters.rs
- src/routes/chains/models.rs
- src/routes/chains/tests/chains.rs
- src/tests/backend_url.rs
- src/tests/json/chains/rinkeby.json
- src/tests/json/chains/rinkeby_disabled_wallets.json
- src/tests/json/chains/rinkeby_enabled_features.json
- src/tests/json/chains/rinkeby_fixed_gas_price.json
- src/tests/json/chains/rinkeby_multiple_gas_price.json
- src/tests/json/chains/rinkeby_no_gas_price.json
- src/tests/json/chains/rinkeby_rpc_auth_unknown.json
- src/tests/json/chains/rinkeby_rpc_no_auth.json
- src/tests/json/chains/rinkeby_unknown_gas_price.json
- `safe_apps_rpc_uri` represents a different RPC url that can be used by the clients in the context of `safe-apps`
-  It was already part of the `/api/v1/chains` of the `safe-config-service` but was never exposed to the clients via the `safe-client-gateway`
> Add safe_apps_rpc_uri to ChainInfo

- src/routes/transactions/routes.rs
Please ignore the branch name. It is unrelated to this fix.
> Documentation fix for `post_transaction`

- src/config/mod.rs
- src/config/tests/mod.rs
- src/routes/balances/handlers_v2.rs
- Use `/v1/safes/{}/balances/` instead of `/v1/safes/{}/balances/usd/` for balances. This was one of the main purposes of the new feature but it was still using the old transaction service route
- Balance requests to the core services now follow `BALANCES_CORE_REQUEST_CACHE_DURATION` which is set to 1 hour by default
- Token requests to the core services are now cached for 10 seconds
> Fix balances route for balances_v2

- Cargo.lock
- Cargo.toml
Changelog: https://github.com/gnosis/safe-client-gateway/compare/v3.10.0...release-v3.10.1
> Bump service version to 3.10.1

- src/common/models/backend/chains.rs
- src/routes/chains/converters.rs
- src/routes/chains/models.rs
- src/routes/chains/tests/chains.rs
- src/tests/backend_url.rs
- src/tests/json/chains/polygon.json
- src/tests/json/chains/rinkeby.json
- src/tests/json/chains/rinkeby_disabled_wallets.json
- src/tests/json/chains/rinkeby_enabled_features.json
- src/tests/json/chains/rinkeby_fixed_gas_price.json
- src/tests/json/chains/rinkeby_multiple_gas_price.json
- src/tests/json/chains/rinkeby_no_gas_price.json
- src/tests/json/chains/rinkeby_rpc_auth_unknown.json
- src/tests/json/chains/rinkeby_rpc_no_auth.json
- src/tests/json/chains/rinkeby_unknown_gas_price.json
See https://github.com/gnosis/safe-config-service/issues/324 for more details
- Add `public_rpc_uri` to `ChainInfo` – this field represents a public RPC URI that can be set with external frameworks/wallets (eg.: metamask)
> Add public_rpc_uri to ChainInfo

- src/main.rs
- Set `broken_intra_doc_links` to level `deny` – see https://doc.rust-lang.org/beta/rustdoc/lints.html#broken_intra_doc_links
- This makes the build return an error if there's a broken link in the docs
> Set broken_intra_doc_links linter to level deny

- src/providers/address_info.rs
- src/routes/transactions/converters/details.rs
- src/routes/transactions/converters/tests/details.rs
- src/routes/transactions/models/details.rs
- src/tests/json/results/tx_details_with_origin.json
Closes #725 
~~Note: in our test json, `Module` transactions for a `multiSend` have the `to` address set to the `safe` address too. Since that is the address we would be checking for, I don't think this feature would behave as expected. Should we be looking in a different field for this address?~~
~~https://github.com/gnosis/safe-client-gateway/blob/main/src/tests/json/transactions/multisig_with_origin.json~~
The test json was pointing rightfully to a different version of the `multiSend` contract
> Introducing `TransactionData::trusted_delegate_call_target` flag 

- Cargo.lock
- Cargo.toml
- src/routes/delegates/handlers.rs
Closes #741 
Missing trailing `/` for delete request to the core services.
> Delegate `DELETE` endpoints missing trailing `/` for core service request

- src/routes/hooks/routes.rs
- src/routes/mod.rs
Closes #749 
Note: we were never consuming the `chainId` returned in the `Payload` from the core services, as we are simply invalidating safes across chains. 
If we have the `chain_id` we can attempt to rebuild the request URL and thusly the cache key, although this change would be much more involved.
> Added chain dependant hook update endpoint

- src/cache/cache_op_executors.rs
- src/cache/tests/cache_op_executors.rs
- src/cache/tests/mod.rs
- src/utils/errors.rs
Closes #745 
The issue was that we were storing in the cache the error json in the body of the request to the backend services, while forwarding the error by just passing the same body as a flat string. 
This change introduces the following:
- We attempt to deserialize into the error structure we know from the core services (`ErrorDetails`)
- if the error contains a structure we don't know, we revert to the old behaviour
- I added a tests to cover both branches
> Atempt http error deserialization

- Cargo.lock
- Cargo.toml
- src/routes/mod.rs
- src/routes/safes/handlers/estimations.rs
- src/routes/safes/models.rs
- src/routes/safes/routes.rs
- src/routes/safes/tests/routes.rs
Closes #757 
- Revert #754 
- Add `v2` estimation endpoint that replaces `latestNonce` with `recommendedNonce`
Example:
Endpoint: `POST - /v2/chains/<chain_id>/safes/<safe_address>/multisig-transactions/estimations`
Example request body:
```json
{
"to": "0xD9BA894E0097f8cC2BBc9D24D308b98e36dc6D02",
"value": "0",
"data": "0x095ea7b3000000000000000000000000ae9844f89d98c150f5e61bfc676d68b4921559900000000000000000000000000000000000000000000000000001c6bf52634000",
"operation": 0
}
```
Assuming the current nonce of the Safe is `7` and the transaction with the highest nonce stored on the service is `76` the following response will be returned:
```json
{
"currentNonce": 7,
"recommendedNonce": 77,
"safeTxGas": "63417"
}
```
`recommendedNonce` can be directly used for proposing a new Safe …
> Closes #757: Fix wrong `latestNonce`

- docker-compose.yml
- Map the `redis` port in `docker-compose.yml` to `localhost:6379`
- This makes it easier to deterministically check if `redis` is running on that port without having to check which port was mapped by Docker
> Map redis port to localhost:6379

- .env.sample
- .github/workflows/rust.yml
- src/cache/cache_op_executors.rs
- src/cache/cache_operations.rs
- src/config/mod.rs
- src/routes/safes/handlers/safes.rs
- src/routes/safes/tests/routes.rs
- src/utils/http_client.rs
Closes #772 
Note: ~~`TRANSACTION_SERVICE_AUTH_TOKEN` is now **expected** . Meaning that if not present, the CGW would panic, failing the request.~~
The env var has been made optional as it is not an integral part of the setup of a CGW instance. However, I left the original error mesasge as a `WARN` level log, to notify developers.
> Added `TRANSACTION_SERVICE_AUTH_TOKEN` and the possibility to add headers to requests

- Cargo.lock
- Cargo.toml
Changelog: https://github.com/gnosis/safe-client-gateway/compare/v3.14.0...bump-safe-config-version
> Bump service version to 3.15.0

- rust-toolchain.toml
- 1.58.0 Release – https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html
- 1.57.0 Release – https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html
> Bump rust from 1.56.0 to 1.58.0

- .github/workflows/rust.yml
- src/common/converters/page_metadata.rs
- src/common/models/page.rs
- src/routes/chains/handlers.rs
- src/routes/chains/models.rs
- src/routes/chains/routes.rs
- src/routes/chains/tests/json/backend_chains_info_page.json
- src/routes/chains/tests/json/expected_chains_info_page.json
- src/routes/chains/tests/mod.rs
- src/routes/chains/tests/routes.rs
- src/routes/transactions/handlers/history.rs
- src/routes/transactions/handlers/mod.rs
- src/routes/transactions/handlers/queued.rs
- src/utils/urls.rs
Closes #762 
- We bundle `limit` and `offset` in `cursor` to generate the `next` and `previous` links for `Page`s of data (like for tx related endpoints)
- Reused as much code as possible from `txHistory` and `txQueued`
- Tested `chain` endpoints
> Pagination fix for `chains` endpoint

- scripts/deploy_docker.sh
- Given the changes to how we do cross-compilation in 69711737511e75d6cc2d2c966ae4bfd1a357a82f, we now need to use `docker buildx build` instead of `docker build`
- BuildX provides additional context which is now required by the new `Dockerfile` (e.g. `BUILDPLATFORM` and `TARGETPLATFORM`
> Use buildx in deploy_docker.sh

- Dockerfile
```bash
rustup component add rustfmt --toolchain nightly
```
PR #1073 removed `ca-certificates`  from  the runtime image. However, it is still required.
screenshot:
> Dockerfile: add ca-certificates
